apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Dev overlay placeholder.
# Typical dev changes:
# - use :dev image tags
# - reduce replicas
# - disable/relax autoscaling
# - use nginx ingress instead of ALB
